version: "3.5"

services:
  api01: &api
    build:
      context: .
    hostname: api01
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "20MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api 
    hostname: api02
    ports:
      - "3000:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

 
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
